###> Install cert-manager
###> cert-manager has some issues connecting to api so it needs a special network policy before installing
    - name: copy network policy
      copy:
        src: kube-files/cert-manager-2-kube-api.yml
        dest: "{{ deploy_path }}/kube-files/cert-manager-2-kube-api.yml"
      register: result
    - debug:
        msg: "{{ result }}"

    - name: Apply policy
      shell: |
        kubectl apply -f "{{ deploy_path }}/kube-files/cert-manager-2-kube-api.yml"
      register: result
    - debug:
        msg: "{{ result }}"

    - name: Install cert-manager
      shell: |
        helm repo add jetstack https://charts.jetstack.io --force-update
        helm repo update
        helm install cert-manager jetstack/cert-manager \
        --namespace cert-manager \
        --create-namespace \
        --set installCRDs=true
      register: result
    - debug:
        msg: "{{ result }}"
