- name: Join Worker nodes to kluster
  hosts: k8swn
  become: true
  gather_facts: false

  tasks:

    - name: Wait for ssh
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local

    - name: Copy join command 
      become: yes
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        mode: get 
        object: kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join workers to the k8s cluster.
      become: yes
      command: /bin/bash /tmp/kubernetes_join_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not }}"
