- name: Test run for new key gen
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
  tasks:
    - name: Remove AWS keypair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        state: absent
      register: result
    - debug:
        msg: "{{ result }}"

